### ISSUE TITLE
How does hooking into MetaMask work?

### ISSUE THREAD

**Issue by Qqwy** [cmditch/mel-bew3#1]
I'd like to use this library regardless of if the user is using Mist, Parity or MetaMask.

How is it possible to hook into e.g. MetaMask instead of using a hard-coded HttpProvider?

**Comment by cmditch** [comment]
Indeed, this library is "wallet agnostic". It is admittedly less convenient in elm to keep in sync with whatever wallet is being used. There is an inescapable chasm between Elm and JS, to ensure the safety and guarantees Elm offers.

This can all be solved through a little elm port/subscription boiler plate. I'll be creating a little npm package soon, along with a tutorial, to help make the developer experience as nice as possible. Until then, I recommend looking at how the example app is keeping track of the user's current account.

This same pattern can be implemented for `web3.version.getNetwork`.

See [this example](https://github.com/cmditch/mel-bew3/blob/master/examples/simple/index.html#L27), for tracking changes in Javascript land, and sending relevant changes into Elm-land.

PS - Please open issues on https://github.com/cmditch/elm-ethereum from here on out. Thanks!
